/*******************************************************************************
 * Copyright (C) 2015 TTTech Automotive GmbH. All rights reserved              *
 * Schoenbrunnerstrasse 7, A-1040 Wien, Austria. office@tttech-automotive.com  *
 ******************************************************************************/
/**
*  \file
*      CtApImageProcess_FreeRunning_EventId.h
*  \brief
*       Automatic generated by gen_dtc_header_files.py (Version :1.5.2)
*       Input: SMTC Component FMS_EP21H2_020_BSW_SAIC20200702.xlsm
*       Sheet: DTCMatrix
*       Date: 2020-08-22 18:23:47
*
*  \version
*       Template version 1.0
*
*/
#ifndef CTAPIMAGEPROCESS_FREERUNNING_EVENTID_H
#define CTAPIMAGEPROCESS_FREERUNNING_EVENTID_H

/*********************************
 * Sender DTCs
 *********************************/

#define DTC_A12F31_360_left_Camera_signal_error 25U
#define DTC_A13031_360_right_Camera_signal_error 43U
#define DTC_A13131_360_front_Camera_signal_error 44U
#define DTC_A13231_360_rear_Camera_signal_error 45U
#define DTC_A11054_Surround_view_has_no_calibration_data_or_surround_view_fails_to_calibrate 31U
#define DTC_9AF44B_360_Camera_Module_Temperature_out_of_range 1U
#define DTC_996297_Camera_View_Unvaliable 11U

/**********************************
 * Receiver DTCs
 **********************************/


#endif /* CTAPIMAGEPROCESS_FREERUNNING_EVENTID_H */