/*** ******************************************************************************/
/*** Copyright (C) 2014 TTTech Automotive GmbH. All rights reserved             ***/
/*** Schoenbrunnerstrasse 7, A-1040 Wien, Austria. office\tttech-automotive.com ***/
/*** ******************************************************************************/
/*** Module Logmap/RTE Interfaces ***/
/*** IFSet version: 1.1.20 ***/
/*** Generated by : sc_logmap ***/

/** \file Logmap.h */

/* PRQA S 0602, 0603 EOF */
/*  0602: Allow TTTech-python-C-libs and CGL; usage of names starting with _.  */
/*  0603: Allow TTTech-python-C-libs and CGL; usage of reserved names.         */
#ifndef _LOGMAP_H
#define _LOGMAP_H

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */


#include "Std_Types.h"

extern const uint8 LogMap [256];

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _LOGMAP_H */
