/*** Module Ra_Transmit, written by TTX-Mwcodegenerator (Version 0.17.0,   ***/
/*** 18-Apr-2018)/Remote_Access (Version 6.3.7, 11-Dec-2019)               ***/
/*** IFSet version: 1.1.20                                                 ***/

/** \file Ra_Transmit.h */

/* double include prevention */
#ifndef RA_TRANSMIT_H
#define RA_TRANSMIT_H

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */


#include "Rte_Type.h"
#include "Ra.h"
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpCOM_BMS_HSC1_100ms Ra_Transmit_CtApComQM_PpCOM_BMS_HSC1_100ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpCOM_BMS_HSC1_100ms Ra_Transmit_CtApComQM_PpCOM_BMS_HSC1_100ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpCOM_BMS_HSC1_100ms Ra_Transmit_CtApComQM_PpCOM_BMS_HSC1_100ms
#define Ra_Transmit_CtApSysManager_PpCOM_BMS_HSC1_100ms Ra_Transmit_CtApComQM_PpCOM_BMS_HSC1_100ms
void Ra_Transmit_CtApComQM_PpCOM_BMS_HSC1_100ms (Dt_RECORD_BMS_HSC1_FrP11 * tDeBMS_HSC1_FrP11);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpCOM_FICM_HSC4_50ms Ra_Transmit_CtApComQM_PpCOM_FICM_HSC4_50ms
#define Ra_Transmit_CtApSysManager_PpCOM_FICM_HSC4_50ms Ra_Transmit_CtApComQM_PpCOM_FICM_HSC4_50ms
void Ra_Transmit_CtApComQM_PpCOM_FICM_HSC4_50ms (Dt_RECORD_FICM_HSC4_FrP13 * tDeFICM_HSC4_FrP13);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpCOM_FICM_HSC4_AVM_100ms Ra_Transmit_CtApComQM_PpCOM_FICM_HSC4_AVM_100ms
void Ra_Transmit_CtApComQM_PpCOM_FICM_HSC4_AVM_100ms
    ( Dt_RECORD_FICM_HSC4_FrP18_FrP35_AVM * tDeFICM_HSC4_FrP18_FrP35_AVM
    , Dt_RECORD_FICM_HSC4_FrP19 * tDeFICM_HSC4_FrP19
    );
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpCOM_FICM_HSC4_AVM_10ms Ra_Transmit_CtApComQM_PpCOM_FICM_HSC4_AVM_10ms
void Ra_Transmit_CtApComQM_PpCOM_FICM_HSC4_AVM_10ms (Dt_RECORD_FICM_HSC4_FrP32 * tDeFICM_HSC4_FrP32);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpCOM_TPMS_HSC3_400ms Ra_Transmit_CtApComQM_PpCOM_TPMS_HSC3_400ms
#define Ra_Transmit_CtApSysManager_PpCOM_TPMS_HSC3_400ms Ra_Transmit_CtApComQM_PpCOM_TPMS_HSC3_400ms
void Ra_Transmit_CtApComQM_PpCOM_TPMS_HSC3_400ms
    ( Dt_RECORD_TPMS_HSC3_FrP01 * tDeTPMS_HSC3_FrP01
    , Dt_RECORD_TPMS_HSC3_FrP02 * tDeTPMS_HSC3_FrP02
    );
  
#define Ra_Transmit_CtApFreeSpaceFusion_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApLaneFusion_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApMiddleMapmatching_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApMwrProcess_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApObstacleFusion_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApParkingLot_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApPathPlanner_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApPrediction_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
#define Ra_Transmit_CtApUltrasonicProcess_PpDR_Merges_10ms Ra_Transmit_CtApDR_PpDR_Merges_10ms
void Ra_Transmit_CtApDR_PpDR_Merges_10ms (Dt_RECORD_DeDR_List * tDeDR_List);
  
#define Ra_Transmit_CtApBISTASIL_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApBISTQM_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApComASILB_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApComASILD_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApComQM_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApDR_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApDSC_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApDiagnosticManager_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApE2ETranASILB_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApE2ETranASILD_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApFreeSpaceFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApHighFrequencyPositioning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApInertialProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApIntegratedPositioning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApInteractionProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApLaneFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApLocBuffer_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMap_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMeProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMiddleMapmatching_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMotionControl_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMwrProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApObstacleFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApParkingLot_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPathPlanner_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPathSolver_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPer_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPer_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPrediction_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApSOMEIPGW_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApStateMonitor_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApSysManager_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApTrafficElementFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApTransformer_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApUSBCom_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApUltrasonicHandler_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApUltrasonicProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdDebug_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdDebug_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdEyeQCom_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdLCSM_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdLCSS_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
void Ra_Transmit_CtApDSC_SH00_PpDiagCoding (Dt_RECORD_Diag_Coding * tDeCoding);
  
#define Ra_Transmit_CtApBISTASIL_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApBISTASIL_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApBISTQM_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApBISTQM_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApComASILB_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApComASILD_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApComQM_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApDR_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApDSC_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApDiagnosticManager_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApE2ETranASILB_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApE2ETranASILD_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApFreeSpaceFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApHighFrequencyPositioning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApHostSupervisionSlave_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApInertialProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApIntegratedPositioning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApInteractionProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApLaneFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApLocBuffer_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMap_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMeProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMiddleMapmatching_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMotionControl_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMwrProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApObstacleFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApParkingLot_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPathPlanner_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPathSolver_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPer_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPer_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPrediction_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApSOMEIPGW_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApSafetyGuardian_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApStateMonitor_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApStbMASIL_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApStbMASIL_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApSysManager_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApTrafficElementFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApTransformer_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApUSBCom_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApUltrasonicHandler_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApUltrasonicProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdDebug_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdDebug_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdErrorHandlerProxy_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdEyeQCom_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdLCSM_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdLCSS_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdTimeMonitor_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
void Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead (Dt_BOOL * tDeFSPCleared);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpDiagImageProcess_FreeRunningRead Ra_Transmit_CtApDSC_SH00_PpDiagImageProcess_FreeRunningRead
void Ra_Transmit_CtApDSC_SH00_PpDiagImageProcess_FreeRunningRead
    ( Dt_RECORD_Routine_Adjust_command_0x5A09_Call * tDeAdjust_command_0x5A09
    , Dt_RECORD_Routine_Check_pre_condition_0x5A01_Call * tDeCheck_pre_condition_0x5A01
    , Dt_RECORD_Routine_Close_EOL_view_0x5A05_Call * tDeClose_EOL_view_0x5A05
    , Dt_RECORD_Routine_Enter_EOL_view_0x5A0C_Call * tDeEnter_EOL_view_0x5A0C
    , Dt_RECORD_Routine_Enter_service_calibration_view_0x5A06_Call * tDeEnter_service_calibration_view_0x5A06
    , Dt_RECORD_Routine_Point_check_and_switch_to_next_view_0x5A07_Call * tDePoint_check_and_switch_to_next_view_0x5A07
    , Dt_RECORD_Routine_Request_calibration_error_code_0x5A0B_Call * tDeRequest_calibration_error_code_0x5A0B
    , Dt_RECORD_Routine_Send_point_status_0x5A08_Call * tDeSend_point_status_0x5A08
    , Dt_RECORD_Routine_Start_calibration_0x5A02_Call * tDeStart_calibration_0x5A02
    );
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpEcuSerialNumber Ra_Transmit_CtApDSC_SH00_PpEcuSerialNumber
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpEcuSerialNumber Ra_Transmit_CtApDSC_SH00_PpEcuSerialNumber
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpEcuSerialNumber Ra_Transmit_CtApDSC_SH00_PpEcuSerialNumber
#define Ra_Transmit_CtApSysManager_PpEcuSerialNumber Ra_Transmit_CtApDSC_SH00_PpEcuSerialNumber
void Ra_Transmit_CtApDSC_SH00_PpEcuSerialNumber (Dt_ARRAY_16_uint8 * tDeEcuSerialNumber);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpVehicleIdentificationNumber Ra_Transmit_CtApDSC_SH00_PpVehicleIdentificationNumber
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpVehicleIdentificationNumber Ra_Transmit_CtApDSC_SH00_PpVehicleIdentificationNumber
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpVehicleIdentificationNumber Ra_Transmit_CtApDSC_SH00_PpVehicleIdentificationNumber
#define Ra_Transmit_CtApSysManager_PpVehicleIdentificationNumber Ra_Transmit_CtApDSC_SH00_PpVehicleIdentificationNumber
#define Ra_Transmit_CtCdEyeQCom_PpVehicleIdentificationNumber Ra_Transmit_CtApDSC_SH00_PpVehicleIdentificationNumber
void Ra_Transmit_CtApDSC_SH00_PpVehicleIdentificationNumber (Dt_ARRAY_17_uint8 * tDeVehicleIdentificationNumber);
  
#define Ra_Transmit_CtApDSC_SH00_PpDiagImageProcess_FreeRunningWrite Ra_Transmit_CtApImageProcess_FreeRunning_PpDiagImageProcess_FreeRunningWrite
void Ra_Transmit_CtApImageProcess_FreeRunning_PpDiagImageProcess_FreeRunningWrite
    ( Dt_RECORD_Routine_Adjust_command_0x5A09_RetVal * tDeAdjust_command_0x5A09
    , Dt_RECORD_Routine_Check_pre_condition_0x5A01_RetVal * tDeCheck_pre_condition_0x5A01
    , Dt_RECORD_Routine_Close_EOL_view_0x5A05_RetVal * tDeClose_EOL_view_0x5A05
    , Dt_RECORD_Routine_Enter_EOL_view_0x5A0C_RetVal * tDeEnter_EOL_view_0x5A0C
    , Dt_RECORD_Routine_Enter_service_calibration_view_0x5A06_RetVal * tDeEnter_service_calibration_view_0x5A06
    , Dt_RECORD_MeasuredValue_ImageProcess_FreeRunning * tDeMeasuredValue_ImageProcess_FreeRunning
    , Dt_RECORD_Routine_Point_check_and_switch_to_next_view_0x5A07_RetVal * tDePoint_check_and_switch_to_next_view_0x5A07
    , Dt_RECORD_Routine_Request_calibration_error_code_0x5A0B_RetVal * tDeRequest_calibration_error_code_0x5A0B
    , Dt_RECORD_Routine_Send_point_status_0x5A08_RetVal * tDeSend_point_status_0x5A08
    , Dt_RECORD_Routine_Start_calibration_0x5A02_RetVal * tDeStart_calibration_0x5A02
    );
  
#define Ra_Transmit_CtApDiagnosticManager_PpImageProcess_FaultCondition_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_FaultCondition_60ms
#define Ra_Transmit_CtApStateMonitor_PpImageProcess_FaultCondition_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_FaultCondition_60ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_FaultCondition_60ms
    ( Dt_RECORD_FaultCondition_BKP_FRP * tDeBKP
    , Dt_RECORD_FailureCondition_FRP * tDeFailureCondition
    , Dt_RECORD_FaultCondition_FRP * tDeFaultCondition
    , Dt_RECORD_TriggerCondition_FRP * tDeTriggerCondition
    );
  
#define Ra_Transmit_CtCdEyeQCom_PpImageProcess_FreeRunning2EyeQCom_100ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_FreeRunning2EyeQCom_100ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_FreeRunning2EyeQCom_100ms (Dt_RECORD_ImageProcess2EyeQ * tDeImageProcess2EyeQ);
  
#define Ra_Transmit_CtApFreeSpaceFusion_PpImageProcess_FreeSpace_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_FreeSpace_60ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_FreeSpace_60ms
    ( Dt_ARRAY_200_uint8_1_0 * tDeBKP
    , Dt_RECORD_SVFreeSpaces * tDeFreeSpcae
    );
  
#define Ra_Transmit_CtApComQM_PpImageProcess_HSC4_AVM_50ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_HSC4_AVM_50ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_HSC4_AVM_50ms (Dt_RECORD_IECU_HSC4_FrP08_SV * tDeIECU_HSC4_FrP08_SV);
  
#define Ra_Transmit_CtApLaneFusion_PpImageProcess_Lane_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Lane_60ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Lane_60ms (Dt_RECORD_SVLanes * tDeSVLanes);
  
#define Ra_Transmit_CtApLocBuffer_PpImageProcess_Location_100ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Location_100ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Location_100ms (Dt_RECORD_SVLocation * tDeFLocation);
  
#define Ra_Transmit_CtApObstacleFusion_PpImageProcess_Obstacle_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Obstacle_60ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Obstacle_60ms (Dt_RECORD_SVObstacles * tDeObstacle);
  
#define Ra_Transmit_CtApParkingLot_PpImageProcess_ParkingLot_20ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_ParkingLot_20ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_ParkingLot_20ms (Dt_RECORD_SVParkingSlot * tDeSVParkingSlot);
  
#define Ra_Transmit_CtApInertialProcess_PpImageProcess_Position_init_status_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Position_init_status_60ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Position_init_status_60ms (Dt_RECORD_Position_init_status * tDePosition_init_status);
  
#define Ra_Transmit_CtApSOMEIPGW_PpImageProcess_ReswevedA2B_50ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_ReswevedA2B_50ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_ReswevedA2B_50ms (Dt_RECORD_ReservedA2B * tDeReservedA2B);
  
#define Ra_Transmit_CtApFreeSpaceFusion_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApLaneFusion_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApLocBuffer_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApObstacleFusion_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApParkingLot_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApUSBCom_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms (Dt_RECORD_SVCameraFail * tDeSurroundCameraFail);
  
#define Ra_Transmit_CtApSOMEIPGW_PpImageProcess_SVData_Upload_status_300ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVData_Upload_status_300ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVData_Upload_status_300ms (Dt_RECORD_SVData_Upload_status * tDeSVData_Upload_status);
  
#define Ra_Transmit_CtApFreeSpaceFusion_PpImageProcess_Status_20ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Status_20ms
#define Ra_Transmit_CtApLaneFusion_PpImageProcess_Status_20ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Status_20ms
#define Ra_Transmit_CtApLocBuffer_PpImageProcess_Status_20ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Status_20ms
#define Ra_Transmit_CtApObstacleFusion_PpImageProcess_Status_20ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Status_20ms
#define Ra_Transmit_CtApParkingLot_PpImageProcess_Status_20ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Status_20ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_Status_20ms (Dt_RECORD_SVStatus * tDeStatus);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpPdImageProcess_FreeRunningRead Ra_Transmit_CtApImageProcess_FreeRunning_PpPdImageProcess_FreeRunningWrite
#define Ra_Transmit_CtApPer_PH00_PpPdImageProcess_FreeRunningRead Ra_Transmit_CtApImageProcess_FreeRunning_PpPdImageProcess_FreeRunningWrite
void Ra_Transmit_CtApImageProcess_FreeRunning_PpPdImageProcess_FreeRunningWrite
    ( Dt_RECORD_ImageProcessSec_Normal * tDeImageProcessSec_Normal
    , Dt_RECORD_ImageProcess_FreeRunning_Normal * tDeImageProcess_FreeRunning_Normal
    , Dt_RECORD_ImageProcess_Normal * tDeImageProcess_Normal
    );
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpInertialProcess_IMUInfo2ImageProcess_10ms Ra_Transmit_CtApInertialProcess_PpInertialProcess_IMUInfo2ImageProcess_10ms
void Ra_Transmit_CtApInertialProcess_PpInertialProcess_IMUInfo2ImageProcess_10ms (Dt_RECORD_FromGPS * tDeInertialProcess_Info);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpParkingLot_Ctrl_40ms Ra_Transmit_CtApParkingLot_PpParkingLot_Ctrl_40ms
void Ra_Transmit_CtApParkingLot_PpParkingLot_Ctrl_40ms (Dt_RECORD_SVCtrl * tDeSVCtrl);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApDR_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApDiagnosticManager_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApFreeSpaceFusion_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApHighFrequencyPositioning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApInertialProcess_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApIntegratedPositioning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApInteractionProcess_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApLaneFusion_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApLocBuffer_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApMap_FreeRunning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApMeProcess_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApMiddleMapmatching_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApMotionControl_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApMwrProcess_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApObstacleFusion_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApParkingLot_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApPathSolver_FreeRunning_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApPrediction_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApSOMEIPGW_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApSafetyGuardian_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApStateMonitor_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApSysManager_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApTrafficElementFusion_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApTransformer_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApUltrasonicHandler_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
#define Ra_Transmit_CtApUltrasonicProcess_PpPathPlanner_Planner2AllModules_100ms Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms
void Ra_Transmit_CtApPathPlanner_PpPathPlanner_Planner2AllModules_100ms (Dt_RECORD_PlannerEnvirInfo * tDePlanner_PlannerEnvirInfo);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpEthernetCom_AVCameraDirt_100ms Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVCameraDirt_100ms
void Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVCameraDirt_100ms (Dt_RECORD_AVCameraDirt * tDeAVCameraDirt);
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpEthernetCom_AVData_Upload_Status_300ms Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVData_Upload_Status_300ms
void Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVData_Upload_Status_300ms (Dt_RECORD_AVData_Upload_Status * tDeAVData_Upload_Status);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApDR_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApDiagnosticManager_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApFreeSpaceFusion_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApHighFrequencyPositioning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApInertialProcess_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApIntegratedPositioning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApInteractionProcess_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApLaneFusion_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApLocBuffer_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApMap_FreeRunning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApMeProcess_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApMiddleMapmatching_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApMotionControl_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApMwrProcess_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApObstacleFusion_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApParkingLot_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApPathPlanner_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApPathSolver_FreeRunning_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApPrediction_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApTrafficElementFusion_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApTransformer_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
#define Ra_Transmit_CtApUltrasonicProcess_PpStateMonitor_FailureAction_50ms Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
void Ra_Transmit_CtApStateMonitor_PpStateMonitor_FailureAction_50ms
    ( Dt_RECORD_FltActnReq * tDeFltActnReq
    , Dt_RECORD_FltIndicator * tDeFltIndicator
    , Dt_RECORD_StateMonitor_BKP * tDeStateMonitor_BKP
    );
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApDR_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApFreeSpaceFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApHighFrequencyPositioning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApInertialProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApIntegratedPositioning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApLaneFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMap_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMeProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApPathSolver_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApPrediction_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApTrafficElementFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApTransformer_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApUSBCom_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApUltrasonicHandler_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApUltrasonicProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
void Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms (Dt_RECORD_DrivingModeSts * tDeDrivingModeSts);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApDR_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
#define Ra_Transmit_CtApTransformer_PpSysManager_MobileyeGenericSensor_10ms Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms
void Ra_Transmit_CtApSysManager_PpSysManager_MobileyeGenericSensor_10ms (Dt_RECORD_MobileyeGenericSensor * tDeMobileyeGenericSensor);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
#define Ra_Transmit_CtApTransformer_PpSysManager_VCUInfo_100ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms
void Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_100ms (Dt_RECORD_VCUStatus5 * tDeVMS_VCUStatus5);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApDR_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApInertialProcess_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
#define Ra_Transmit_CtApTransformer_PpSysManager_VCUInfo_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
void Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_10ms
    ( Dt_RECORD_VMS_BKP * tDeVMS_BKP
    , Dt_RECORD_VCUStatus10 * tDeVMS_VCUStatus10
    , Dt_RECORD_VCUStatus2 * tDeVMS_VCUStatus2
    , Dt_RECORD_VCUStatus9 * tDeVMS_VCUStatus9
    );
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
#define Ra_Transmit_CtApTransformer_PpSysManager_VCUInfo_200ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
void Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_200ms
    ( Dt_RECORD_VCUStatus8 * tDeVCUStatus8
    , Dt_RECORD_VCUStatus7 * tDeVMS_VCUStatus7_200ms
    );
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApDR_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
#define Ra_Transmit_CtApTransformer_PpSysManager_VCUInfo_20ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms
void Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_20ms (Dt_RECORD_VCUStatus3 * tDeVMS_VCUStatus3);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApDR_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
#define Ra_Transmit_CtApTransformer_PpSysManager_VCUInfo_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms
void Ra_Transmit_CtApSysManager_PpSysManager_VCUInfo_50ms (Dt_RECORD_VCUStatus4 * tDeVMS_VCUStatus4);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApDR_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
#define Ra_Transmit_CtApTransformer_PpSysManager_VCUStatus1_10ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms
void Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus1_10ms (Dt_RECORD_VCUStatus1 * tDeVMS_VCUStatus1);
  
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApDR_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApMotionControl_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApSafetyGuardian_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
#define Ra_Transmit_CtApTransformer_PpSysManager_VCUStatus6_50ms Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms
void Ra_Transmit_CtApSysManager_PpSysManager_VCUStatus6_50ms (Dt_RECORD_VCUStatus6 * tDeVMS_VCUStatus6);
  
#define Ra_Transmit_CtApComQM_PpUltrasonicHandler_HSC1_PDC_50ms Ra_Transmit_CtApUltrasonicHandler_PpUltrasonicHandler_HSC1_PDC_50ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpUltrasonicHandler_HSC1_PDC_50ms Ra_Transmit_CtApUltrasonicHandler_PpUltrasonicHandler_HSC1_PDC_50ms
void Ra_Transmit_CtApUltrasonicHandler_PpUltrasonicHandler_HSC1_PDC_50ms (Dt_RECORD_IECU_HSC1_PDC_FrP00 * tDeIECU_HSC1_PDC_FrP00);
  
#define Ra_Transmit_CtApComQM_PpUltrasonicHandler_PDC_CHCAN_50ms Ra_Transmit_CtApUltrasonicHandler_PpUltrasonicHandler_PDC_CHCAN_50ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpUltrasonicHandler_PDC_CHCAN_50ms Ra_Transmit_CtApUltrasonicHandler_PpUltrasonicHandler_PDC_CHCAN_50ms
void Ra_Transmit_CtApUltrasonicHandler_PpUltrasonicHandler_PDC_CHCAN_50ms
    ( Dt_RECORD_PDC_HSC2_FrP00 * tDePDC_HSC2_FrP00
    , Dt_RECORD_PDC_HSC2_FrP01 * tDePDC_HSC2_FrP01
    );
  
#define Ra_Transmit_CtApFreeSpaceFusion_PpUltrasonicProcess_Dists_20ms Ra_Transmit_CtApUltrasonicProcess_PpUltrasonicProcess_Dists_20ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpUltrasonicProcess_Dists_20ms Ra_Transmit_CtApUltrasonicProcess_PpUltrasonicProcess_Dists_20ms
#define Ra_Transmit_CtApObstacleFusion_PpUltrasonicProcess_Dists_20ms Ra_Transmit_CtApUltrasonicProcess_PpUltrasonicProcess_Dists_20ms
#define Ra_Transmit_CtApParkingLot_PpUltrasonicProcess_Dists_20ms Ra_Transmit_CtApUltrasonicProcess_PpUltrasonicProcess_Dists_20ms
#define Ra_Transmit_CtApPathPlanner_PpUltrasonicProcess_Dists_20ms Ra_Transmit_CtApUltrasonicProcess_PpUltrasonicProcess_Dists_20ms
void Ra_Transmit_CtApUltrasonicProcess_PpUltrasonicProcess_Dists_20ms
    ( Dt_RECORD_UltrasonicProcess_BKP * tDeUltrasonicProcess_BKP
    , Dt_RECORD_UltrasonicDists * tDeUltrasonicProcess_Dists
    );
  
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpEyeQCom2ImageProcess_FreeRunning_300ms Ra_Transmit_CtCdEyeQCom_PpEyeQCom2ImageProcess_FreeRunning_300ms
void Ra_Transmit_CtCdEyeQCom_PpEyeQCom2ImageProcess_FreeRunning_300ms (Dt_RECORD_EyeQ2ImageProcess * tDeEyeQ2ImageProcess);
  
#define Ra_Transmit_CtApBISTASIL_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApBISTASIL_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApBISTQM_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApBISTQM_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApComASILB_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApComASILD_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApComQM_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDR_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDSC_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDSC_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDiagnosticManager_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApE2ETranASILB_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApE2ETranASILD_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApFreeSpaceFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApHighFrequencyPositioning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApHostSupervisionSlave_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApInertialProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApIntegratedPositioning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApInteractionProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApLaneFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApLocBuffer_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMap_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMeProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMiddleMapmatching_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMotionControl_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMwrProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApObstacleFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApParkingLot_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPathPlanner_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPathSolver_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPer_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPer_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPrediction_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApSOMEIPGW_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApSafetyGuardian_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApStateMonitor_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApStbMASIL_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApStbMASIL_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApSysManager_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApTrafficElementFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApTransformer_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApUSBCom_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApUltrasonicHandler_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApUltrasonicProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdDebug_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdDebug_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdErrorHandlerProxy_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdEyeQCom_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdLCSS_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdTimeMonitor_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
void Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
    ( Dt_IFSET_VERSION * tDeIFSETVersion
    , Dt_ENUM_LCS_State * tDeLCSPH00State
    , Dt_ENUM_LCS_State * tDeLCSSH00State
    , Dt_ENUM_LCS_State * tDeLCSSH01State
    , Dt_ENUM_LCS_State * tDeLCSSystemState
    , Dt_ENUM_VAR_HWVariant * tDeVARHWVariant
    );
  
#define Ra_Transmit_CtApBISTASIL_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApBISTASIL_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApBISTQM_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApBISTQM_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApCoarseTrackMatching_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApComASILB_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApComASILD_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApComQM_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDR_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDSC_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDSC_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDiagnosticManager_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApE2ETranASILB_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApE2ETranASILD_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApFreeSpaceFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApHighFrequencyPositioning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApHostSupervisionSlave_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApInertialProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApIntegratedPositioning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApInteractionProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApLaneFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApLocBuffer_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMapSourcing_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMap_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMeProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMiddleMapmatching_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMotionControl_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMwrProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApObstacleFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApParkingLot_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPathPlanner_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPathSolver_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPer_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPer_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPrediction_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApSOMEIPGW_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApSafetyGuardian_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApStateMonitor_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApStbMASIL_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApStbMASIL_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApSysManager_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApTrafficElementFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApTransformer_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApUSBCom_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApUltrasonicHandler_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApUltrasonicProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdDebug_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdDebug_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdErrorHandlerProxy_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdEyeQCom_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdLCSS_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdTimeMonitor_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
void Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
    ( Dt_RECORD_StbmTimestamp * tDeBuildDate
    , Dt_BuildRevision * tDeBuildRevision
    , Dt_Record_Version * tDePlatformVersion
    , Dt_ARRAY5_ReleaseType * tDeReleaseType
    , Dt_IFSET_VERSION * tDeSystemVersion
    );
  


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* RA_TRANSMIT_H */
